application: greenupapp
version: 2-5
runtime: python27
api_version: 1
threadsafe: false

skip_files: 
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^android/.*
- ^ios/.*
- ^svgs/.*

handlers:

- url: /dash
  static_dir: web/dash/

- url: /favicon.ico
  static_files: api/favicon.ico
  upload: api.favicon.ico

- url: /greenup_logo.png
  mime_type: image/png
  static_files: greenup_logo.png
  upload: greenup_logo.png

- url: /iphone_black.png
  mime_type: image/png
  static_files: iphone_black.png
  upload: iphone_black.png

- url: /api/heatmap
  script: api.controllers.heatmap.application

- url: /api/pins
  script: api.controllers.pins.application

- url: /api/comments
  script: api.controllers.comments.application

- url: /api/debug
  script: api.controllers.debug.application

- url: /api 
  script: api.controllers.api.application

- url: /(.+)
  static_files: web/client/\1
  upload: web/client/(.+)

- url: /
  script: detector.application

- url: /.*
  script: api.controllers.api.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest