application: greenupapi
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /api/heatmap
  script: controllers.heatmap.application

- url: /api/pins
  script: controllers.pins.application

- url: /api/comments
  script: controllers.comments.application

- url: /api/debug
  script: controllers.debug.application

- url: /.*
  script: api.application

libraries:
- name: webapp2
  version: latest