application: greenup
version: 1-01
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /api/comments
  script: comments.application

- url: /api 
  script: api.application

- url: /.*
  script: api.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

